[window]
# decorations = "None"
opacity = 1.0
padding = { x = 10, y = 10 }

[font]
normal = { family = "JetBrainsMono Nerd Font"}
size = 12
offset = { x = 0, y = 2}

[colors.primary]
background = "#1f1f28"
foreground = "#dcd7ba"

[colors.normal]
black = "#090618"
red = "#c34043"
green = "#76946a"
yellow = "#c0a36e"
blue = "#7e9cd8"
magenta = "#957fb8"
cyan = "#6a9589"
white = "#c8c093"

[colors.bright]
black = "#727169"
red = "#e82424"
green = "#98bb6c"
yellow = "#e6c384"
blue = "#7fb4ca"
magenta = "#938aa9"
cyan = "#7aa89f"
white = "#dcd7ba"

[env]
TERM = 'xterm-256color'
