- name: Install nvm
  shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash

- name: Install Node.js
  shell: '. {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install node'
  args:
    executable: /bin/bash

- name: Install latest pnpm
  shell: '. {{ ansible_env.HOME }}/.nvm/nvm.sh && npm install -g pnpm'
  args:
    executable: /bin/bash
